query ($id: ID!){
	Project(id: $id) {
			id
			name
			createdAt
      sensors {
        id
        name
        unit
				factor
        sensorData(first: 10, orderBy: createdAt_DESC) {
          id
          value
          createdAt
        }
      }
		}
}
